<?php
defined('SK_ENTRY') or die('Access Denied!'); 

include $this->getScriptPath('manage-nav.phtml'); 
include $this->getScriptPath('message-general.phtml'); 
?>

<div class="navindex_title"><?=$this->lang->_('Change password')?></div>

<form id="user_profilepw" name="user_profilepw" action="<?=$this->basePath?>/user/manage-profile/pwdupdate" method="post" >
	<table width="100%" border="0" cellpadding="0" cellspacing="10" >
  		<tr>
    		<td width="20%" align="right" ><?=$this->lang->_('Current password')?> :</td>
    		<td width="20px"></td>
    		<td ><input id="pwold" name="pwold" type="password" /></td>
  		</tr>
  		<tr>
    		<td align="right" ><?=$this->lang->_('New password')?> :</td>
    		<td></td>
    		<td ><input id="pwnew" name="pwnew" type="password" /></td>
  		</tr>
  		<tr>
    		<td align="right" ><?=$this->lang->_('Confirm new password')?> :</td>
    		<td></td>
    		<td ><input id="repwnew" name="repwnew" type="password" /></td>
  		</tr>
  		<tr>
    		<td></td>
    		<td></td>
    		<td ><input class="input_button" type="submit" name="submit" value="<?=$this->lang->_('Submit')?>" /></td>
  		</tr>
	</table>
</form>

