<?php 

include $this->getScriptPath('manage-nav.phtml'); 

include $this->getScriptPath('message-general.phtml'); 
?>

<div class="navindex_title"><?=$this->lang->_('Manage')?> <?=$this->lang->_('Bookmarks')?> (<a href="<?=$this->baseModulePath?>/manage-node/new" align="absmiddle" >Add new</a>)</div>

<style type="text/css">
.item_list tr td {padding: 3px 8px 4px 8px; border-bottom:#c6d9e9 1px solid;}
.item_list .draggAbleOdd {background-color: #e4f2fd;}
.item_list .draggAbleEven {background-color: #ffffff;}
</style>

<table class="item_list" width="100%" border="0" cellpadding="0" cellspacing="0" >
	<tr>
	    <td width="10px"></td>
    	<td><b><?=$this->lang->_('Name')?></b></td>
    	<td><b><?=$this->lang->_('Location')?></b></td>
		<td><b><?=$this->lang->_('Category')?></b></td>
    	<td><b><?=$this->lang->_('Weight')?></b></td>
		<td><b><?=$this->lang->_('Created')?></b></td>
		<td></td>
	</tr>
    <?php 
    $even = 'Even';
    foreach ($this->nodeList as $node): 
    ?>
	<tr class="draggAble<?php echo $even = ($even == 'Even') ? 'Odd' : 'Even';?>">
	    <td></td>
		<td><a href="<?=$this->baseModulePath?>/manage-node/edit/nodeid/<?=$node['nodeid']?>"><?=$node['title']?></a></td>
		<td><a href="<?=$node['body']?>" target="_blank"><?=$node['body']?></a></td>
		<td><?=$node['tree_name']?></td>
		<td><?=$node['ordering']?></td>
		<td><?=$node['created']?></td>
		<td align="right">
		    <a href="<?=$this->baseModulePath?>/manage-node/delete/nodeid/<?=$node['nodeid']?>" class="aButtonText"><?=$this->lang->_('Delete')?></a>
		    <a href="<?=$this->baseModulePath?>/manage-node/edit/nodeid/<?=$node['nodeid']?>" class="aButtonText"><?=$this->lang->_('Edit')?></a>
		</td>
	</tr>
	<?php endforeach; ?> 
</table>


