<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="<?=$this->metaRobots?>" />
    <meta name="description" content="" />
    <meta name="keywords" content="<?=$this->metaKeywords?>" />
    <meta name="author" content="" />
    <title><?=$this->title?></title>
    <link rel="stylesheet" href="<?=$this->tplDefPath?>/css/global.css" type="text/css" media="all" />
    <link rel="stylesheet" href="<?=$this->tplPath?>/css/myhome.css" type="text/css" media="all" />
</head>
<body>
