<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>An error occurred</title>
    <link rel="stylesheet" href="<?=$this->viewDefaultPath?>/css/common.css" type="text/css" media="all" />
    <link rel="stylesheet" href="<?=$this->viewDefaultPath?>/css/error.css" type="text/css" media="all" />
</head>
<body>
<div class="errorbody">
<div class="errorbox">
<table width="100%" border="0" cellspacing="0" cellpadding="0"><tr>
    <td class="msgicon" valign="top">
        <img src="<?=$this->viewDefaultPath?>/img/notice-large.png" />
    </td>
    <td>
        <h1 class="msgtitle">An error occurred</h1>
        <p class="msgbody"><b><?php echo $this->message ?></b></p>
    </td>
</tr></table>
</div>
<?php if ('development' == APPLICATION_ENV): ?>
<div class="errorbox">
    <div class="msgtitle">Exception information</div>
    <p class="msgbody"><?php echo $this->exception->getMessage() ?></p>
    <div class="msgtitle">Stack trace</div>
    <p class="msgbody"><?php echo nl2br($this->exception->getTraceAsString()) ?></p>
    <div class="msgtitle">Request Parameters</div>
    <p class="msgbody"><?php echo nl2br(var_export($this->request->getParams(), true)) ?></p>
</div>
<?php endif ?>
</div>
</body>
</html>
