<?php defined('SK_ENTRY') or die('Access Denied!'); ?>
<div class="nodeRightBar">
    <h4><?=$this->lang->_('Archives')?></h4>
    <ul>
        <?php foreach ($this->archives as $archive): ?>
        <li><img src="<?=$this->tplPath?>/img/bullet_blue.png" border="0" align="absmiddle" /> <a href="<?=$this->basePath?>/home/<?=$this->profile['username']?>/<?=$this->subModule?>/node/list/date/<?=$archive['year']?>-<?=$archive['month']?>"><?=$archive['year']?>/<?=$archive['month']?> [<?=$archive['count']?>]</a></li>			
        <?php endforeach;?>
    </ul>
</div>
