<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php echo $this->headTitle() ?>
    <link rel="stylesheet" href="<?=$this->viewDefaultPath?>/css/common.css" type="text/css" media="all" />
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
</head>
<body>
<?php 
//echo $this->render('general-topnav.phtml');
?>
<div class="wrapper">
<?php echo $this->layout()->content; ?>
</div>

<div id="footer" class="wrapper aligncenter">
    <p>Powered by <a href="#" target="_blank">SYS</a></p>
</div>
</body>
</html>
