<?php
include $this->getScriptPath('message-general.phtml'); 
?>
<div class="center_box">
    <div class="navindex_title"><?=$this->lang->_('Sign up')?></div>

    <form action="<?=$this->baseModulePath?>/sign/create" method="post" id="register_form">
    <table width="100%" border="0" cellpadding="0" cellspacing="10">
        <tr>
            <td width="220px" align="right" ><b><?=$this->lang->_('Username')?></b></td>
            <td>
                <input id="username" name="username" type="text" size="20" value="<?=$this->reg['username']?>" />
            </td>
        </tr>
       <tr>
            <td align="right"><b><?=$this->lang->_('Password')?></b></td>
            <td>
                <input id="password" name="password" type="password" size="20" value="<?=$this->reg['password']?>" />
            </td>
       </tr>
       <tr>
            <td align="right"><b><?=$this->lang->_('Re-type Password')?></b></td>
            <td><input id="repassword" name="repassword" type="password" size="20" value="<?=$this->reg['repassword']?>" /></td>
       </tr>
       <tr>
            <td align="right"><b><?=$this->lang->_('Birthday')?></b></td>
            <td><input id="birthday" name="birthday" type="text" size="15"  maxlength="10" value="<?=$this->reg['birthday']?>" />  <?=$this->lang->_('Example')?></b> 1970-01-01</td>
       </tr>
       <tr>
            <td align="right"><b><?=$this->lang->_('Email')?></b></td>
            <td><input id="email" name="email" type="text" size="30" maxlength="50" dataType="Email" value="<?=$this->reg['email']?>" /></td>
       </tr>
       <tr>
            <td align="right"></td>
            <td><input class="input_button" type="submit" value="<?=$this->lang->_('Sign up')?>" /></td>
       </tr>
    </table>
    </form>
</div>

