<?php 
include $this->getScriptPath('htmlheader.phtml');
?>

<style>
body {padding:100px; background-color:#e4f2fd;}
#msg_container {text-align:left; background-color:#ffffff; border:#c6d9e9 3px solid;}
#msg_container td {padding:20px;}
#msg_container .msg_body {padding-top:10px; font-size:14pt; font-weight:bold; border-bottom:#c6d9e9 1px solid;}
#msg_container ul {padding:20px 0px 20px 5px;}
#msg_container ul li {list-style-type:none;}
#msg_container a {text-decoration:underline;}
</style>

<div class="centerbox">
<table id="msg_container" width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      	<td width="80px" align="center" valign="top">
      	    <img src="<?=$this->tplDefPath?>/img/<?=$this->message['type']?>-large.png" border="0" />
      	</td>
      	<td>
      	    <div class="msg_body"><?=$this->message['body']?></div>
      	    <ul>
      	        <?php foreach ($this->message['links'] as $link): ?> 
      	        <li>&#8250; <a href="<?=$link['url']?>"><?=$link['title']?></a></li>
      	        <?php endforeach; ?>
      	    </ul>
      	</td>
    </tr>
</table>
</div>

<?php 
include $this->getScriptPath('htmlfooter.phtml');
?>
