<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php echo $this->headTitle() ?>
    <link rel="stylesheet" href="<?=$this->viewDefaultPath?>/css/common.css" type="text/css" media="all" />
    <?php echo $this->headLink() ?>
</head>

<body>
<?php 
echo $this->render('general-topnav.phtml');
echo $this->render('general-header.phtml');
echo $this->render('message-general.phtml');
?>

<div class="wrapper">
<?php echo $this->layout()->content; ?>
</div>

<?php
$gdb = Zend_Registry::get('db');
//print_r($gdb->getProfiler()->getQueryProfiles());
?>
<div id="footer" class="wrapper">
    <p>
        Powered by <a href="http://smartkit.sourceforge.net" target="_blank">SYSNULL</a> 
        &nbsp;&nbsp; Queries <?=$gdb->getProfiler()->getTotalNumQueries()?>@<?=$gdb->getProfiler()->getTotalElapsedSecs()?>
    </p>
</div>
</body>
</html>
