<?php 
$this->headLink()->appendStylesheet($this->viewModulePath.'/css/manage.css');

include $this->getScriptPath('message-general.phtml'); 
?>

<div id="profile-manage">
<h2 class="title">My Profile</h2>
<!-- TinyMCE/ -->
<script type="text/javascript" src="<?=$this->basePath?>/_default/js/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="<?=$this->basePath?>/_default/js/editor.js"></script>
<script type="text/javascript">
  tinymceInitOptions['content_css'] = "<?=$this->basePath?>/_default/js/editor.css";
  tinyMCE.init(tinymceInitOptions);
</script>
<!-- /TinyMCE -->

<form id="user_profile" name="user_profile" action="<?=$this->basePath?>/user/profile-manage/do" method="post" >
  <input id="uid" name="uid" type="hidden" value="<?=$this->profile['uid']?>" />
  <table class="box" width="100%" border="0" cellpadding="0" cellspacing="8" >
    <tr>
      <td width="120px" align="right" ><b>My name</b></td>
      <td width="20px"></td>
      <td><input id="name" name="name" type="text" size="16" value="<?=$this->profile['name']?>" /></td>
    </tr>
    <tr>
      <td align="right" ><b>Gender</b></td>
      <td></td>
      <td>
      	Male <input id="gender" name="gender" type="radio" value="1" <?php if ($this->profile['gender'] == 1) { echo 'checked="checked"'; } ?> />
          Female <input name="gender" type="radio" value="0" <?php if ($this->profile['gender'] == 0) { echo 'checked="checked"'; } ?> />   
      </td>
    </tr>
    <tr>
      <td align="right" ><b>Birthday</b></td>
      <td></td>
      <td ><input id="birthday" name="birthday" type="text" size="16" value="<?=$this->profile['birthday']?>" /> Example : 1970-01-01</td>
    </tr>
    <tr>
      <td align="right" ><b>Address</b></td>
      <td></td>
      <td ><input id="address" name="address" type="text" size="30" value="<?=$this->profile['address']?>" /></td>
    </tr>
    <tr>
      <td align="right" valign="top" ><b>About me</b></td>
      <td></td>
      <td>
        <div id="switchEditorsBar" class="hideifnojs">	
	      <a href="javascript:;" onclick="richEditor.go('desc', 'tinymce');">[Visual]</a>
          <a href="javascript:;" onclick="richEditor.go('desc', 'html');">[HTML]</a>
        </div>
        <textarea id="desc" name="desc" style="width:100%" rows="20" ><?=$this->profile['desc']?></textarea>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><input class="input_button" type="submit" name="submit" value="Save" /></td>
    </tr>
  </table>
</form>
<script>
  document.getElementById('switchEditorsBar').className = '';
  tinyMCE.execCommand("mceAddControl", false, 'desc');
</script>
</div>
