<?php
$this->headLink()->appendStylesheet($this->viewModulePath.'/css/manage.css');
include $this->getScriptPath('message-general.phtml'); 
?>
<div class="managecommon">
<h2 class="title">Change photo</h2>
<div class="box">
<p>You can upload a JPG, GIF, or PNG file. (Maximum size of 500KB) Do not upload photos containing children, pets, cartoons, celebrities, nudity, artwork or copyrighted images.</p>
<form id="changephoto" name="changephoto" enctype="multipart/form-data" action="<?=$this->basePath?>/user/profile-manage/photodo" method="post">
  	<table border="0" cellpadding="0" cellspacing="0" >
  	    <tr>
  	        <td width="160px"><b>Select picture</b></td>
  	        <td><input id="attachment" name="attachment" size="40" type="file" /></td>
  	    </tr>
  	    <tr>
  	        <td></td>
  	        <td><input type="submit" value="Upload" />
  	    </tr>
  	</table>
</form>
</div>
</div>
