<?php
include $this->getScriptPath('myhome-htmlheader.phtml');
?>
<div id="bodywrap">
    <div id="bodycontent">

        <?php
        include $this->getScriptPath('myhome-topnav.phtml');
        include $this->getScriptPath('userhome-header.phtml');
        ?>
        
        <div class="myhomeCenterFrame">
        
            <?php include $this->getScriptPath('message-general.phtml'); ?>

            <!-- pageDepthNavBox/ -->
            <div class="pageDepthNavBox">
                <a href="<?php echo $this->basePath?>/home/<?php echo $this->profile['username']?>/<?php echo $this->subModule?>/"><img src="<?=$this->tplPath?>/img/house.png" /> <b><?=$this->lang->_('My Home')?></b></a>
            </div>
            <!-- /pageDepthNavBox -->

            <!-- leftbox/ -->
	        <div id="node-leftbox">
	            <?php foreach ($this->nodeList as $node): ?> 
	        	<div class="node-list">
	        	    <div class="hinfo">
	        	        <h3><a href="<?=$this->userHomeModuleUri?>/<?=$node['href']?>"><?=$node['title']?></a></h3>
	        	        <div>
	        	            <img src="<?=$this->tplPath?>/img/date.png" /> <?php echo date('Y-m-d', strtotime($node['created']));?>
	        	            <img src="<?=$this->tplPath?>/img/folder.png" /> <a href="<?=$this->userHomeModuleUri?>/node/list?treeid=<?=$node['treeid']?>"><?=$this->trees[$node['treeid']]['name']?></a>
               		        <img src="<?=$this->tplPath?>/img/tag_blue.png" /> 
               		        <?php foreach ((array)$node['termList'] as $term): ?> 
               		        &nbsp;<a href="<?=$this->userHomeModuleUri?>/node/list?term=<?=$term?>"><?=$term?></a>
               		        <?php endforeach; ?>
	        	        </div>
                	</div>
       		   		<div class="nodeEntry"><?=$node['body']?></div>
               		<div class="binfo clear_both">
	        	        <img src="<?=$this->tplPath?>/img/comments.png" /> <a href="<?=$node['href']?>#comment-list"><?=$this->lang->_('Comments')?> (<?=$node['count_comment']?>)</a>
                        <img src="<?=$this->tplPath?>/img/folder_page.png" /> <a href="<?=$node['href']?>"><?=$this->lang->_('Views')?> (<?=$node['count_access']?>)</a>
                        <?php if ($node['allowDelete']) { ?>
                        <img src="<?=$this->tplPath?>/img/page_delete.png" /> <a href="<?=$this->userHomeModuleUri?>/node/delete/?nodeid=<?=$node['nodeid']?>"><?=$this->lang->_('Delete')?></a>
                        <?php } ?>
               		</div>
	            </div>
	            <?php endforeach; ?> 
              
                <div class="centerbox">
                <?php 
                $pager = $this->nodePager;
                $pagerUrl = $this->nodeUrl;
                include $this->getScriptPath('pager.phtml'); 
                ?>
                </div>
	        </div>
	        <!-- /leftbox -->
	        
	        <!-- rightbox/ -->
	        <div id="node-rightbox">
            <?php 
            include $this->getScriptPath('myhome-widgets-search.phtml');
            include $this->getScriptPath('myhome-widgets-tree.phtml');
            include $this->getScriptPath('myhome-widgets-comment.phtml');
            ?>
            </div>
            <!-- /rightbox -->
            
        </div>
        
    </div>
</div>
<?php
include $this->getScriptPath('general-footer.phtml');
include $this->getScriptPath('htmlfooter.phtml');
?>
