<?php
$this->headLink()->appendStylesheet($this->viewModulePath.'/css/common.css');
?>
<div id="profile">
    <h2 class="title">Profile</h2>
    <table class="box" width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td width="160px" valign="top"><img src="/home/<?=$this->user['uname']?>/user/profile/photo/w100.png" /></td>
            <td align="left" class="info"><?=$this->profile['desc']?></td>
        </tr>
    </table>
</div>

