<?php
$this->headLink()->appendStylesheet($this->viewModulePath.'/css/manage.css');
?>

<h2 class="title">Add Content Type</h2>
<form id="type_admin_create" name="type_admin_create" action="<?=$this->basePath?>/wcm/type-admin/createpost" method="post">
  <table width="100%" border="0" cellpadding="0" cellspacing="10" >
    <tr>
      <td width="200px">Type ID</td>
      <td><input id="typeid" name="typeid" type="text" /></td>
    </tr>
    <tr>
      <td>Name</td>
      <td><input id="title" name="title" type="text" maxlength="32" /></td>
    </tr>
    <tr>
      <td>Description</td>
      <td><input id="summary" name="summary" type="text" /></td>
    </tr>
    <tr>
      <td></td>
      <td><input type="submit" name="submit" value="Submit" /></td>
    </tr>
  </table>
</form>

