<?php
//$this->headLink()->appendStylesheet($this->viewDefaultPath.'/codemirror/css/docs.css');
include $this->getScriptPath('message-general.phtml'); 
?>

<h1>Manage layouts (<?php echo $this->typeid?>)</h1>

<form id="layout_edit" name="layout_edit" action="<?=$this->basePath?>/wcm/layout-admin/update" method="post">
<input id="typeid" name="typeid" type="hidden" value="<?php echo $this->typeid?>" />
<input id="name" name="name" type="hidden" value="<?php echo $this->name?>" />

<div style="border: 1px solid black; padding: 3px;">
<textarea id="source" name="source" cols="120" rows="30"><?php echo $this->source?></textarea>
</div>
<input type="submit" name="submit" value="Submit" />
</form>

<script src="<?php echo $this->viewDefaultPath?>/codemirror/js/codemirror.js" type="text/javascript"></script>
<script type="text/javascript">
  var editor = CodeMirror.fromTextArea('source', {
    height: "500px",
    parserfile: ["parsexml.js", "parsecss.js", "tokenizejavascript.js", "parsejavascript.js", "parsehtmlmixed.js"],
    stylesheet: ["<?php echo $this->viewDefaultPath?>/codemirror/css/xmlcolors.css", "<?php echo $this->viewDefaultPath?>/codemirror/css/jscolors.css", "<?php echo $this->viewDefaultPath?>/codemirror/css/csscolors.css"],
    path: "<?php echo $this->viewDefaultPath?>/codemirror/js/"
  });
</script>

