<?php
include $this->getScriptPath('message-general.phtml'); 
?>

<h1>Manage layouts (<?php echo $this->typeid?>)</h1>

<table width="100%" border="1" cellpadding="0" cellspacing="2">
<tr>
    <td>Name</td>
    <td>Operations</td>
</tr>
<tr>
    <td>Entry index</td>
    <td>
        <a href="/wcm/layout-admin/edit?typeid=<?php echo $this->typeid?>&name=index">Edit</a> 
    </td>
</tr>
<tr>
    <td>Entry list</td>
    <td>
        <a href="/wcm/layout-admin/edit?typeid=<?php echo $this->typeid?>&name=list">Edit</a> 
    </td>
</tr>
<tr>
    <td>Entry view</td>
    <td>
        <a href="/wcm/layout-admin/edit?typeid=<?php echo $this->typeid?>&name=view">Edit</a> 
    </td>
</tr>
</table>
