<?php
defined('SK_ENTRY') or die('Access Denied!'); 

include $this->getScriptPath('admin-nav.phtml'); 

include $this->getScriptPath('message-general.phtml'); 
?>

<div class="navindex_title"><?=$this->lang->_('Change password')?></div>

<form id="user_profilepw" name="user_profilepw" action="<?=$this->basePath?>/user/admin-user/savepwd" method="post" >
<input id="userid" name="userid" type="hidden" value="<?=$this->userid?>"/>
	<table width="100%" border="0" cellpadding="0" cellspacing="10" >
  		<tr>
    		<td align="right" width="260px"><b><?=$this->lang->_('New password')?></b></td>
    		<td></td>
    		<td ><input id="pwdnew" name="pwdnew" type="password" /></td>
  		</tr>
  		<tr>
    		<td align="right" ><b><?=$this->lang->_('Confirm new password')?></b></td>
    		<td></td>
    		<td ><input id="repwdnew" name="repwdnew" type="password" /></td>
  		</tr>
  		<tr>
    		<td></td>
    		<td></td>
    		<td ><input class="input_button" type="submit" name="submit" value="<?=$this->lang->_('Submit')?>" /></td>
  		</tr>
	</table>
</form>

