
<style>
.layout_section {margin:0 auto; width:100%;}
.sidebar { float:left; width:200px; height:500px; background:#9c6;}
.sidebar2 { float:right; width:200px; height:500px; background:#9c6;}
.content { margin:0 210px !important; margin:0 205px; height:500px; background:#ffa;}
</style>

<div class="layout_section">
    <ul class="sidebar droptrue">adfa</ul>
    <ul class="sidebar2"></ul>
    <ul class="content"></ul>
</div>


