<?php
$this->headLink()->appendStylesheet($this->viewModulePath.'/css/manage.css');
include $this->getScriptPath('message-general.phtml'); 
?>
<div class="managecommon">
<h2 class="title">Edit email</h2>
<form id="account_email" name="account_email" action="<?=$this->basePath?>/user/account-manage/emaildo" method="post" >
  <table class="box" width="100%" border="0" cellpadding="0" cellspacing="10" >
    <tr>
      <td width="200px" align="right" >Email</td>
      <td ><input id="email" name="email" type="text" value="<?php echo $this->profile['email']?>" /></td>
    </tr>
    <tr>
      <td></td>
      <td ><input type="submit" name="submit" value="Submit" /></td>
    </tr>
  </table>
</form>
</div>
