<?php 
defined('SK_ENTRY') or die('Access Denied!');

include $this->getScriptPath('admin-nav.phtml');

include $this->getScriptPath('message-general.phtml'); 
?>


<div class="navindex_title"><?=$this->lang->_('Roles')?> (<a href="<?=$this->basePath?>/<?=$this->subModule?>/admin-role/add" align="absmiddle" >Add new</a>)</div>

<style type="text/css">
.item_list tr td {padding: 3px 8px 4px 8px; border-bottom:#c6d9e9 1px solid;}
.item_list .prlist {background-color:#e7eff7;}
.item_list .draggAbleOdd {background-color: #e4f2fd;}
.item_list .draggAbleEven {background-color: #ffffff;}
</style>

<table class="item_list" width="100%" border="0" cellpadding="0" cellspacing="0" >
	<tr>
		<td><b><?=$this->lang->_('Name')?></b></td>
		<td><b><?=$this->lang->_('Operations')?></b></td>
		<td align="right"></td>
	</tr>
    <?php 
    $even = 'Even';
    foreach ($this->roles as $role): 
    ?> 
	<tr class="draggAble<?php echo $even = ($even == 'Even') ? 'Odd' : 'Even';?>">
		<td><?=$role['name']?></td>
        
		<td>
		    <a href="<?=$this->basePath?>/<?=$this->subModule?>/admin-role/edit/?roleid=<?=$role['roleid']?>" class="aButtonText"><?=$this->lang->_('edit role')?></a>
		</td>
        <td>
            <?php if ($role['ispermedit']) { ?>
		    <a href="<?=$this->basePath?>/<?=$this->subModule?>/admin-role/permedit/?roleid=<?=$role['roleid']?>" class="aButtonText"><?=$this->lang->_('edit permissions')?></a>
            <?php } else { ?>
            <?=$this->lang->_('locked')?>
            <?php } ?>
		</td>
	</tr>
	<?php endforeach; ?> 
</table>


